version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Path to backend Dockerfile
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile  # Path to frontend Dockerfile
    ports:
      - "3000:3000"
