version: '3.8'  # Specify a version for better compatibility

services:
  backend:
    build:
      context: .  # Path to the backend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    depends_on:
      - frontend  # This ensures that the frontend starts after the backend
    command: npm start

  frontend:
    build:
      context: ./client  # Path to the frontend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: serve -s build --single
