name: Build and deploy Node.js app to Azure Web App - quantumhr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install backend dependencies for build
      - name: Install backend dependencies
        run: npm install

      - name: Install frontend dependencies and build
        working-directory: ./client
        run: |
          npm install
          npm run build 

      - name: Copy React build to backend
        run: cp -r ./client/build ./build

      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -x node_modules/\* -x client/node_modules/\* -x .git/\* -x .github/\* -x tests/\* -x logs/\* -x *.md

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Reinstall dependencies before deploying to ensure everything is set up properly
      - name: Install backend dependencies before deployment
        run: npm install

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'quantumhr'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_87C44E12B9674535A6FCF6F9D15012C1 }}
          package: .
