# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Container App

on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/main_quantumvacations.yml'

  # Allow manual trigger 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'  # Use the latest LTS version of Node.js

      # Install backend and frontend dependencies
      - name: Install dependencies
        run: |
          npm install
          npm install --prefix client
      
      # Build frontend
      - name: Build frontend
        run: |
          npm run build --prefix client

      # Run tests if any
      - name: Run tests
        run: |
          npm run test --if-present

      # Upload artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            . 
            !node_modules
            !client/node_modules
          if-no-files-found: warn

  deploy:
    runs-on: ubuntu-latest
    needs: build
  
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      
      # Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      # Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      #Build and push container to registry
      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: quantumvacationsregistry.azurecr.io
          registryUsername: ${{ secrets.QUANTUMVACATIONSAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.QUANTUMVACATIONSAPP_REGISTRY_PASSWORD }}
          containerAppName: quantumvacationsapp
          resourceGroup: DefaultResourceGroup-CQ
          imageToBuild: quantumvacationsregistry.azurecr.io/quantumvacationsapp:${{ github.sha }}
