name: Build and deploy Node.js app to Azure Web App - quantumhr

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old artifacts
        uses: actions/delete-artifact@v1
        with:
          age: 5 # Deletes artifacts older than 5 days

  build:
    runs-on: ubuntu-latest
    needs: cleanup

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js version
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install backend dependencies using npm ci (faster and deterministic)
      - name: Install backend dependencies
        run: npm ci

      # Install frontend dependencies and build the frontend
      - name: Install frontend dependencies and build
        working-directory: ./client
        run: |
          npm ci
          npm run build

      # Copy frontend build to backend
      - name: Copy React build to backend
        run: cp -r ./client/build ./build

      # Zip the backend including frontend build, excluding unnecessary files
      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -x node_modules/\* -x client/node_modules/\* -x .git/\* -x .github/\* -x tests/\* -x logs/\* -x *.md

      # Upload the zipped artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      # Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Unzip the artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Login to Azure using service principal
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CFB30A8F71EE4D2FAC1D3A0D16351E88 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_17B4FB278711448ABAD9EA57573DB02A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_007E344BC335424E845D31347001C69B }}

      # Deploy the app to Azure Web App using the publish profile
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'quantumhr'
          slot-name: 'Production'
          package: .
