name: Build and deploy Node.js app to Azure Web App - quantumvacations

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install backend dependencies
      - name: Install backend dependencies
        run: npm install

      # Install frontend dependencies and build React app
      - name: Install frontend dependencies and build
        working-directory: ./client # Navigate to React app directory
        run: |
          npm install
          npm run build

      # Copy React build files to backend
      - name: Copy React build to backend
        run: cp -r ./client/build ./build

      # Zip only the necessary files for deployment, excluding unnecessary ones
      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -x node_modules/\* -x client/node_modules/\* -x .git/\* -x .github/\* -x tests/\* -x logs/\* -x *.md

      # Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'quantumvacations'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8F24D8390E784EE7A221869A59128E07 }}
