name: Trigger auto deployment for quantumvacationsapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/quantumvacationsapp-AutoDeployTrigger-8ee9ce29-aaef-4436-a9ed-5e195aa76265.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.QUANTUMVACATIONSAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.QUANTUMVACATIONSAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.QUANTUMVACATIONSAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: quantumvacationsregistry.azurecr.io
          registryUsername: ${{ secrets.QUANTUMVACATIONSAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.QUANTUMVACATIONSAPP_REGISTRY_PASSWORD }}
          containerAppName: quantumvacationsapp
          resourceGroup: DefaultResourceGroup-CQ
          imageToBuild: quantumvacationsregistry.azurecr.io/quantumvacationsapp:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


